// GENERATED by scripts/syncCardDrafts.mjs — do not edit by hand.
// Snapshot of the card_drafts table (the Card Editor is the source of
// truth for card data); re-run `npm run sync-cards` to refresh. Only
// drafts marked Ready for review are included — marking a card ready in
// the editor is what publishes it into the game (see
// src/data/draftCards.ts for how this merges over the static pools).
import type { CardDraftSnapshotEntry } from './draftCards';

export const CARD_DRAFTS_SNAPSHOT: CardDraftSnapshotEntry[] = [
];
