// GENERATED by scripts/syncCardDrafts.mjs — do not edit by hand.
// Snapshot of the card_drafts table (the Card Editor is the source of
// truth for card data); re-run `npm run sync-cards` to refresh. Only
// Published drafts are included — the editor's Publish button is what
// ships a card into the game (see src/data/draftCards.ts for how this
// merges over the static pools). Their rendered images live in
// public/cards/published/, also managed by the sync script.
import type { CardDraftSnapshotEntry } from './draftCards';

export const CARD_DRAFTS_SNAPSHOT: CardDraftSnapshotEntry[] = [
];
